services:
  collection_server:
    image: photoncat/collection_server
    ports:
      - 33333:33333
    volumes:
      - ./mysql_root_password:/mysql/mysql_root_password
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD_FILE: /mysql/mysql_root_password
  mysql:
    image: mysql:5.7
    volumes:
      - cardcollection-develop-mysql-data:/var/lib/mysql
      - ./mysql_root_password:/mysql/mysql_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /mysql/mysql_root_password
      MYSQL_DATABASE: card_collection
  envoy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - 8888:8888
      - 9901:9901
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
  collection_webapp:
    image: photoncat/collection_web_app
    ports:
      - 23333:23333
    
volumes:
  cardcollection-develop-mysql-data: